### ISSUE TITLE
[BUG] bunkerweb-ui not starting / exits on error in Linux integration

### ISSUE THREAD

**Issue by chrismade** [bunkerity/bunkerweb#362] opened 2022-11-18 09:54 UTC
**Description**

bunkerweb-ui not starting / exits on error in Linux integration

when I edit `/opt/bunkerweb/ui/main.py` and `/opt/bunkerweb/ui/src/ConfigFiles.py` and add the prefix `ui.` to anything which either starts with `src.` or `utils.` then the service starts as expected - but I'm not sure if this is the intended way by the developers to fix this

**How to reproduce**

With a fresh install of bunkerweb 1.4.4 in Linux integration (here Debian bullseye) following the official instructions you will find service "bunkerweb-ui" not started - neither after reboot nor when trying to (re-)start manually - I changed the password in `/etc/bunkerweb/ui.env` but that does not fix the situation 

**Logs**

with `journalctl -xe --no-pager` you will find this relevant section:

```
Nov 18 10:39:38 debian11w bunkerweb-ui.sh[7190]: Starting UI
Nov 18 10:39:40 debian11w bunkerweb-ui.sh[7191]: Usage: python -m flask run [OPTIONS]
Nov 18 10:39:40 debian11w bunkerweb-ui.sh[7191]: Try 'python -m flask run --help' for help.
Nov 18 10:39:40 debian11w bunkerweb-ui.sh[7191]: Error: While importing 'ui.main', an ImportError was raised:
Nov 18 10:39:40 debian11w bunkerweb-ui.sh[7191]: Traceback (most recent call last):
Nov 18 10:39:40 debian11w bunkerweb-ui.sh[7191]:   File "/opt/bunkerweb/deps/python/flask/cli.py", line 218, in locate_app
Nov 18 10:39:40 debian11w bunkerweb-ui.sh[7191]:     __import__(module_name)
Nov 18 10:39:40 debian11w bunkerweb-ui.sh[7191]:   File "/opt/bunkerweb/ui/main.py", line 40, in <module>
Nov 18 10:39:40 debian11w bunkerweb-ui.sh[7191]:     from src.ConfigFiles import ConfigFiles
Nov 18 10:39:40 debian11w bunkerweb-ui.sh[7191]: ModuleNotFoundError: No module named 'src'
Nov 18 10:39:40 debian11w systemd[1]: bunkerweb-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by TheophileDiot** [comment] 2022-11-18 10:04
Hi @chrismade, thank you for reporting this issue. Apparently the linux tests weren't precise enough

**Comment by fl0ppy-d1sk** [comment] 2022-11-26 00:41
Hello @chrismade,

It should be fixed in the [v1.4.5 release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.4.5).

**Comment by chrismade** [comment] 2022-11-27 20:43
@fl0ppy-d1sk I'm afraid only half of the occurrences had been fixed - 

3 lines in 2 files have not been fixed - pls find filenames and linenumbers here - all missing the "ui." prefix to either "utils" or "src":

```
err#1
  File "/opt/bunkerweb/ui/src/ConfigFiles.py", line 6, in <module>
    from utils import path_to_dict

err#2
  File "/opt/bunkerweb/ui/main.py", line 46, in <module>
    from utils import (

err#3
  File "/opt/bunkerweb/ui/main.py", line 61, in <module>
    from src.Instances import Instances
```

another issue is new - after I add the missing "ui." prefix to the files/lines above I can manually start

`/opt/bunkerweb/scripts/bunkerweb-ui.sh start`

successfully 


```
Starting UI
 * Serving Flask app '/opt/bunkerweb/ui/main.py'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:7000
Press CTRL+C to quit
```

- but trying to start in context of systemd by

` service bunkerweb-ui start` will unsuccessfully result in

```
Nov 27 21:19:20 debian11w systemd[1]: bunkerweb-ui.service: Start request repeated too quickly.
Nov 27 21:19:20 debian11w systemd[1]: bunkerweb-ui.service: Failed with result 'exit-code'.
The unit bunkerweb-ui.service has entered the 'failed' state with result 'exit-code'.
Nov 27 21:19:20 debian11w systemd[1]: Failed to start BunkerWeb UI service.
```
 
as there is still no official upgrade procedure I installed the 1.4.5 upgrade over 1.4.4 following these instructions:


```
## as root
# step1: stop all services
systemctl stop bunkerweb
systemctl stop bunkerweb-ui
systemctl stop nginx
systemctl disable nginx

# step2: check file date
ls -l /usr/share/doc/bunkerweb/changelog.gz
 
# step3: make backup
mkdir /root/backupbw144
cd /opt/
tar cvzf /root/backupbw144/backup.tgz bunkerweb
cp /opt/bunkerweb/ui.env /opt/bunkerweb/variables.env /root/backupbw144

# step 4: get new package but *DO NOT* use built in "install" method
mkdir /root/bunkerweb145
cd /root/bunkerweb145
curl -k -v -L -o bunkerweb_1.4.5_amd64.deb "https://packagecloud.io/bunkerity/bunkerweb/packages/debian/bullseye/bunkerweb_1.4.5_amd64.deb/download.deb?distro_version_id=207"

# unpack 1
ar x bunkerweb_1.4.5_amd64.deb

# unpack 2
tar xvzf data.tar.gz

find etc opt/bunkerweb/ui usr | cpio -pdmv /

# step5: check file date again, must be 26-Nov-2022 now
ls -l /usr/share/doc/bunkerweb/changelog.gz

# step 6: reboot
init 6

# step 7: after reboot - check logfile for errors
sudo journalctl -xe --no-pager

```

**Comment by fl0ppy-d1sk** [comment] 2023-02-13 18:41
Looks like I can't reproduce your issue with a fresh install of BW 1.4.5 on Debian bullseye.

@AxyFr : any idea ?

**Comment by fl0ppy-d1sk** [comment] 2023-05-02 19:51
Hello @chrismade,

May I ask you to test the last [v1.5.0-beta release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.5.0-beta) and open a new issue if needed ?

**Closed by fl0ppy-d1sk** 2023-05-02 19:51 UTC
Labels: bug
