### ISSUE TITLE
[BUG] scheduler crash when checking for changes in the database 

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#654] opened 2023-09-22 23:58 UTC
### What happened?

scheduler crash when checking for changes in the database 

### How to reproduce?

idk. maybe after a docker restart bunkerweb bw-scheduler

### Relevant log output

```shell
ep 23 01:53:14 172.16.1.1 94e38a563a05[20112]: [2023-09-22 23:53:14] - SCHEDULER - ❌ - An error occurred when checking for changes in the database : Traceback (most recent call last):
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     self.dialect.do_execute(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/engine/default.py", line 921, in do_execute
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     cursor.execute(statement, parameters)
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/cursors.py", line 153, in execute
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     result = self._query(query)
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:              ^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/cursors.py", line 322, in _query
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     conn.query(q)
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/connections.py", line 558, in query
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/connections.py", line 822, in _read_query_result
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     result.read()
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/connections.py", line 1200, in read
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     first_packet = self.connection._read_packet()
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/connections.py", line 739, in _read_packet
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     packet_header = self._read_bytes(4)
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:                     ^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/connections.py", line 795, in _read_bytes
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     raise err.OperationalError(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]: pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]: The above exception was the direct cause of the following exception:
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]: Traceback (most recent call last):
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/db/Database.py", line 322, in check_changes
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     .first()
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:      ^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/orm/query.py", line 2743, in first
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     return self.limit(1)._iter().first()  # type: ignore
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:            ^^^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/orm/query.py", line 2842, in _iter
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:                                                   ^^^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/orm/session.py", line 2262, in execute
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     return self._execute_internal(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:            ^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/orm/session.py", line 2144, in _execute_internal
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     result: Result[Any] = compile_state_cls.orm_execute_statement(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     result = conn.execute(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:              ^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/engine/base.py", line 1412, in execute
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     return meth(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:            ^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     return connection._execute_clauseelement(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     ret = self._execute_context(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:           ^^^^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/engine/base.py", line 1844, in _execute_context
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     return self._exec_single_context(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     self._handle_dbapi_exception(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     self.dialect.do_execute(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/sqlalchemy/engine/default.py", line 921, in do_execute
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     cursor.execute(statement, parameters)
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/cursors.py", line 153, in execute
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     result = self._query(query)
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:              ^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/cursors.py", line 322, in _query
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     conn.query(q)
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/connections.py", line 558, in query
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/connections.py", line 822, in _read_query_result
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     result.read()
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/connections.py", line 1200, in read
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     first_packet = self.connection._read_packet()
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/connections.py", line 739, in _read_packet
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     packet_header = self._read_bytes(4)
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:                     ^^^^^^^^^^^^^^^^^^^
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:   File "/usr/share/bunkerweb/deps/python/pymysql/connections.py", line 795, in _read_bytes
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:     raise err.OperationalError(
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]: [SQL: SELECT bw_metadata.custom_configs_changed AS bw_metadata_custom_configs_changed, bw_metadata.external_plugins_changed AS bw_metadata_external_plugins_changed, bw_metadata.config_changed AS bw_metadata_config_changed, bw_metadata.instances_changed AS bw_metadata_instances_changed 
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]: FROM bw_metadata 
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]: WHERE bw_metadata.id = %(id_1)s 
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]:  LIMIT %(param_1)s]
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]: [parameters: {'id_1': 1, 'param_1': 1}]
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]: (Background on this error at: https://sqlalche.me/e/20/e3q8)
Sep 23 01:53:14 172.16.1.1 94e38a563a05[20112]: [2023-09-22 23:53:14] - ENTRYPOINT - ℹ️  - Scheduler stopped
```

### BunkerWeb version

dev

### What integration are you using?

Docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment] 2023-09-23 11:18
Hi @thelittlefireman, thank you for opening this issue. Interestingly you got this error `Lost connection to MySQL server during query` 🤔
Could you provide us with your configuration if possible ? Thank you :pray:

**Comment by TheophileDiot** [comment] 2023-10-03 14:10
Bump @thelittlefireman

**Comment by fl0ppy-d1sk** [comment] 2023-10-31 09:39
Duplicate of #717

**Closed by fl0ppy-d1sk** 2023-10-31 09:39 UTC
Labels: bug
